### ISSUE TITLE
Doesn't start web process automatically with multibuildpacks

### ISSUE THREAD

**Issue by jshou** [CHH/heroku-buildpack-php#168]
I've been using this buildpack in conjunction with @ddollar's [heroku-buildpack-multi](https://github.com/ddollar/heroku-buildpack-multi), but the default_process_type listed in bin/release doesn't run. I manually created a Procfile that calls "bin/run" and then it starts, but it seems like this shouldn't be necessary. I'm not entirely sure if this is a problem within this buildpack, or with how I'm using it in conjunction with the multibuildpack, but I'd appreciate some feedback, thanks!

**Comment by stof** [comment]
The multi buildpack uses the process defined by the last buildpack of the list. Make sure the PHP buildpack comes last if you want it to run the process automatically.

**Comment by jshou** [comment]
Ah, thanks!
