### ISSUE TITLE
 !     Push rejected, no Cedar-supported app detected HINT: This occurs when Heroku cannot detect the buildpack       to use for this application automatically. See https://devcenter.heroku.com/articles/buildpacks

### ISSUE THREAD

**Issue by Macmee** [CHH/heroku-buildpack-php#170]
!     Push rejected, no Cedar-supported app detected
HINT: This occurs when Heroku cannot detect the buildpack
      to use for this application automatically.
See https://devcenter.heroku.com/articles/buildpacks

**Comment by stof** [comment]
This buildpack is not registered to be detected automatically (there is an official PHP buildpack btw). It must be used explicitly.

and you need to have either a composer.lock or an index.php at the root
