### ISSUE TITLE
Deployment failed on Heroku Cedar-14

### ISSUE THREAD

**Issue by sunfffd** [CHH/heroku-buildpack-php#181]
Hello,
Heroku is forcing container updates to cedar-14.
However after migration, the deployment failed.

-----> Fetching set buildpack https://github.com/CHH/heroku-buildpack-php... done
-----> PHP (composer.json) app detected
-----> Bundling NGINX 1.4.4
       Checksums match. Fetching from cache.
-----> Bundling PHP 5.5.24
       Checksums match. Fetching from cache.
-----> Bundling extensions
       apcu
       Checksums match. Fetching from cache.
       phpredis
       Checksums match. Fetching from cache.
       mongo
       Checksums match. Fetching from cache.
 !     Script error in /tmp/buildpack20151113-159-152d9us/bin/compile on or near line 380
 !     Push rejected, failed to compile PHP (composer.json) app

line 380 should be 
pear config-set php_ini /app/vendor/php/etc/php.ini &> /dev/null

The development branch works, however

**Comment by stof** [comment]
are you using the master or development branch ? cedar-14 support is not yet in master (it will go in master tomorrow)

**Comment by sunfffd** [comment]
Great to know that!

I used the master branch.
